Fantasy-Football/src/Fantasy-Football/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Fantasy_Football.Models;
using Fantasy_Football.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Fantasy_Football.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var games =  _context.NflGames.Where(game => game.Week == "4");
            List<NflGame> gameList = new List<NflGame>();
            foreach(var game in games)
            {
                gameList.Add(game);
            }
            return View(gameList);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
        public IActionResult Admin()
        {
            return View();
        }
        public async Task<IActionResult> UpdatePlayers()
        {
           
            var players = Player.GetPlayers();
            foreach (var player in players)
            {
                _context.Player.Add(player);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
        public async Task<IActionResult> UpdateGames()
        {
            _context.Database.ExecuteSqlCommand("TRUNCATE TABLE [NflGames]");
            var games = NflGame.GetGames();
            foreach (var game in games)
            {
                _context.NflGames.Add(game);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Fantasy-Football/src/Fantasy-Football/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Fantasy_Football.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Fantasy_Football.Controllers
{
    public class NewsController : Controller
    {
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var news = await NflNews.GetFeeds();
            return View(news);
        }
    }
}

Fantasy-Football/src/Fantasy-Football/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fantasy_Football.Data;
using Fantasy_Football.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Fantasy_Football.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public TeamsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Teams
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Team.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .Include(t => t.PlayersTeams).ThenInclude(pt => pt.Player)
                .Include(t => t.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            ViewData["Players"] = new SelectList(_context.Player.OrderBy(player => player.Name), "Id", "Name");
            ViewData["CurrentTeamId"] = id;
            Console.WriteLine(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        [Authorize]
        public IActionResult Create()
        {
            var user = _userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            ViewData["UserId"] = user.Id;
            return View();
        }

        // POST: Teams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User,Name")] Team team)
        {

            if (ModelState.IsValid)
            {
                var user = await _userManager.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                team.User = user;
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction("MyTeams","UserNavigation");
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team.SingleOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ApplicationUserId,Name")] Team team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team.SingleOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Team.Include(t => t.PlayersTeams).SingleOrDefaultAsync(m => m.Id == id);
            _context.Team.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TeamExists(int id)
        {
            return _context.Team.Any(e => e.Id == id);
        }
        [HttpPost]
        [Authorize]
        public async Task<Player> Assign(int PlayerId, int TeamId)
        {
            var team = await _context.Team.FirstOrDefaultAsync(t => t.Id == TeamId);
            var player = await _context.Player.FirstOrDefaultAsync(p => p.Id == PlayerId);
            PlayersTeams newPlayersTeams = new Models.PlayersTeams { Player = player, Team = team };
            _context.Entry(team).State = EntityState.Modified;
            _context.Entry(player).State = EntityState.Modified;
            _context.Add(newPlayersTeams);
            await _context.SaveChangesAsync();
            return player;


        } 
    }
}

Fantasy-Football/src/Fantasy-Football/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>I designed this app to combat the bloat seen on other Fantasy Football sites including ads, videos and other unneccessary information popping up when you didnt want it.  It is designed to be a light-weight solution to modern app software problems.</p>

Fantasy-Football/src/Fantasy-Football/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>NOTE: This button only needs to be clicked *ONCE* per week</p>
<h2><a asp-area="" asp-controller="Home" asp-action="UpdatePlayers">Update Players</a></h2>
<h2><a asp-controller="Home" asp-action="UpdateGames">Update Games</a></h2>

Fantasy-Football/src/Fantasy-Football/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>



<address>
    <strong>Support:</strong> <a href="mailto:mreyez@gmail.com">mreyez@gmail.com</a><br />
</address>

Fantasy-Football/src/Fantasy-Football/Views/Home/Index.cshtml
@model List<Fantasy_Football.Models.NflGame>
@{
    ViewData["Title"] = "Home Page";
}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/images/FieldGrass.jpg" alt="Football Grass" class="img-responsive carousel-image" />
                <div class="carousel-caption" role="option">
                    <p>
                        Play Fantasy Football on a lightweight mobile platform.
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/FootballTexture.jpg" alt="Football Texture" class="img-responsive carousel-image" />
                <div class="carousel-caption" role="option">
                    <p>
                        Create and Manage Leagues. Quickly. Easily. Securly.

                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>*@

<div class="col-sm-3">
    <h2>Scores - Week 4</h2>
    <div class="game-scores">
        @foreach (var game in Model)
        {
            @Html.Partial("~/Views/News/GameScore.cshtml", game)
        }
    </div>
</div>

<div class="col-sm-6">
    <h2>News</h2>
    @Html.Partial("~/Views/News/News.cshtml", await NflNews.GetFeeds())
    <a asp-controller="News" asp-action="Index">More News -></a>
</div>

<div class="col-sm-3 navigation-col">
    <div class="row">
        <div class="col-sm-12">
            <h2>My Profile</h2>
            <ul>
                <li><a asp-area="" asp-controller="UserNavigation" asp-action="MyTeams">My Teams</a></li>
                <li><a asp-area="" asp-controller="Teams" asp-action="Create">Create Teams</a></li>
                <li><a asp-area="" asp-controller="Players" asp-action="Index">View Players</a></li>
            </ul>
        </div>
    </div>
</div>